from pathlib import Path
p=Path('public/mobile-v2.html')
s=p.read_text()
old='function destroyLive(){const f=document.getElementById("v2LiveOwner");if(f){try{f.src="about:blank"}catch(e){}f.remove()}const st=document.getElementById("v2LiveStandby");if(st)st.style.display=""}\nfunction mountLive(){destroyLive();const box=document.getElementById("v2LiveMount"),st=document.getElementById("v2LiveStandby");if(!box)return;if(st)st.style.display="none";const f=document.createElement("iframe");f.id="v2LiveOwner";f.title="SoulCinema Live";f.allow="autoplay; fullscreen; picture-in-picture";f.setAttribute("allowfullscreen","");f.setAttribute("scrolling","no");f.style.cssText="position:absolute;inset:0;width:100%;height:100%;border:0;background:#000;opacity:0;z-index:2";box.style.position="relative";box.style.background="#000";box.appendChild(f);let shown=false;const reveal=()=>{if(shown||!f.isConnected)return;shown=true;f.style.transition="opacity .28s ease";f.style.opacity="1"};f.addEventListener("load",()=>setTimeout(reveal,700),{once:true});setTimeout(reveal,2400);f.src=LIVE_FEED}'
new='let liveWatchTimer=null,liveCheckBusy=false;\nfunction stopLiveWatch(){if(liveWatchTimer){clearTimeout(liveWatchTimer);liveWatchTimer=null}liveCheckBusy=false}\nfunction destroyLive(){stopLiveWatch();const f=document.getElementById("v2LiveOwner");if(f){try{f.src="about:blank"}catch(e){}f.remove()}const st=document.getElementById("v2LiveStandby");if(st){st.style.display="";st.textContent="OFF AIR · STANDBY"}}\nfunction showLiveOwner(){if(document.getElementById("v2LiveOwner")||!document.getElementById("live")?.classList.contains("active"))return;const box=document.getElementById("v2LiveMount"),st=document.getElementById("v2LiveStandby");if(!box)return;if(st)st.style.display="none";const f=document.createElement("iframe");f.id="v2LiveOwner";f.title="SoulCinema Live";f.allow="autoplay; fullscreen; picture-in-picture";f.setAttribute("allowfullscreen","");f.setAttribute("scrolling","no");f.style.cssText="position:absolute;inset:0;width:100%;height:100%;border:0;background:#000;opacity:0;z-index:2";box.style.position="relative";box.style.background="#000";box.appendChild(f);let shown=false;const reveal=()=>{if(shown||!f.isConnected)return;shown=true;f.style.transition="opacity .28s ease";f.style.opacity="1"};f.addEventListener("load",()=>setTimeout(reveal,700),{once:true});setTimeout(reveal,2400);f.src=LIVE_FEED}\nasync function checkLive(){if(liveCheckBusy||!document.getElementById("live")?.classList.contains("active"))return;liveCheckBusy=true;let live=null;try{const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),3500);const r=await fetch("/api/live-status?ts="+Date.now(),{cache:"no-store",signal:ctl.signal});clearTimeout(tm);if(r.ok){const d=await r.json();if(d?.live===true)live=true;else if(d?.live===false)live=false}}catch(e){}liveCheckBusy=false;if(!document.getElementById("live")?.classList.contains("active"))return;const owner=document.getElementById("v2LiveOwner"),st=document.getElementById("v2LiveStandby");if(live===true){if(!owner)showLiveOwner()}else if(live===false){if(owner){try{owner.src="about:blank"}catch(e){}owner.remove()}if(st){st.style.display="";st.textContent="OFF AIR · STANDBY"}}liveWatchTimer=setTimeout(checkLive,4000)}\nfunction mountLive(){destroyLive();const box=document.getElementById("v2LiveMount"),st=document.getElementById("v2LiveStandby");if(!box)return;box.style.position="relative";box.style.background="#000";if(st){st.style.display="";st.textContent="OFF AIR · STANDBY"}checkLive()}'
if old not in s: raise SystemExit('Live baseline signature not found; refusing unsafe patch')
s=s.replace(old,new,1)
marker='@media (orientation:landscape){'
if marker not in s: raise SystemExit('Landscape marker not found')
landscape='@media (orientation:landscape){body.v2-cinema-landscape{overflow:hidden!important;background:#000!important}body.v2-cinema-landscape .app{padding:0!important;min-height:100dvh!important}body.v2-cinema-landscape #live.active{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;padding:0!important;margin:0!important;background:#000!important;z-index:2147482990!important}body.v2-cinema-landscape #live.active>.back,body.v2-cinema-landscape #live.active>.roomHero>.eyebrow,body.v2-cinema-landscape #live.active>.roomHero>h1,body.v2-cinema-landscape #live.active>.roomHero>p,body.v2-cinema-landscape #live.active>.roomHero>.note{display:none!important}body.v2-cinema-landscape #live.active>.roomHero{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;padding:0!important;margin:0!important;border:0!important;border-radius:0!important;background:#000!important;box-shadow:none!important}body.v2-cinema-landscape #v2LiveMount{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;min-width:100vw!important;min-height:100dvh!important;max-width:none!important;max-height:none!important;margin:0!important;border:0!important;border-radius:0!important;z-index:2147483000!important;background:#000!important;overflow:hidden!important}body.v2-cinema-landscape #v2LiveOwner{position:absolute!important;inset:0!important;width:100vw!important;height:100dvh!important;min-width:100%!important;min-height:100%!important;border:0!important;background:#000!important}}\n'
s=s.replace(marker,landscape+marker,1)
p.write_text(s)
